In [48]:
import pandas as pd

In [49]:
df_bureau = pd.read_csv(r"C:\Users\hamza\Masaüstü\Mlops_Lecture_Project\data_folder\bureau.csv", encoding="unicode_escape")

df_bureau.columns

Index(['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE', 'CREDIT_CURRENCY',
       'DAYS_CREDIT', 'CREDIT_DAY_OVERDUE', 'DAYS_CREDIT_ENDDATE',
       'DAYS_ENDDATE_FACT', 'AMT_CREDIT_MAX_OVERDUE', 'CNT_CREDIT_PROLONG',
       'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT',
       'AMT_CREDIT_SUM_OVERDUE', 'CREDIT_TYPE', 'DAYS_CREDIT_UPDATE',
       'AMT_ANNUITY'],
      dtype='str')

In [50]:
df_bureau.head()

,SK_ID_CURR,SK_ID_BUREAU,CREDIT_ACTIVE,CREDIT_CURRENCY,DAYS_CREDIT,CREDIT_DAY_OVERDUE,DAYS_CREDIT_ENDDATE,DAYS_ENDDATE_FACT,AMT_CREDIT_MAX_OVERDUE,CNT_CREDIT_PROLONG,AMT_CREDIT_SUM,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_SUM_LIMIT,AMT_CREDIT_SUM_OVERDUE,CREDIT_TYPE,DAYS_CREDIT_UPDATE,AMT_ANNUITY
0,215354,5714462,Closed,currency 1,-497,0,-153.0,-153.0,NaN,0,91323.0,0.0,NaN,0.0,Consumer credit,-131,NaN
1,215354,5714463,Active,currency 1,-208,0,1075.0,NaN,NaN,0,225000.0,171342.0,NaN,0.0,Credit card,-20,NaN
2,215354,5714464,Active,currency 1,-203,0,528.0,NaN,NaN,0,464323.5,NaN,NaN,0.0,Consumer credit,-16,NaN
3,215354,5714465,Active,currency 1,-203,0,NaN,NaN,NaN,0,90000.0,NaN,NaN,0.0,Credit card,-16,NaN
4,215354,5714466,Active,currency 1,-629,0,1197.0,NaN,77674.5,0,2700000.0,NaN,NaN,0.0,Consumer credit,-21,NaN

In [51]:
df_bureau['CREDIT_TYPE'].unique()

<StringArray>
[                             'Consumer credit',
                                  'Credit card',
                                     'Mortgage',
                                     'Car loan',
                                    'Microloan',
       'Loan for working capital replenishment',
                'Loan for business development',
                             'Real estate loan',
                         'Unknown type of loan',
                         'Another type of loan',
                    'Cash loan (non-earmarked)',
           'Loan for the purchase of equipment',
                         'Mobile operator loan',
                             'Interbank credit',
 'Loan for purchase of shares (margin lending)']
Length: 15, dtype: str

In [52]:
df_bureau.groupby(["SK_ID_CURR" , "CREDIT_ACTIVE"])

In [53]:
bureau_agg = df_bureau.groupby(["SK_ID_CURR" ])['SK_ID_BUREAU'].count().reset_index()
bureau_agg = bureau_agg.rename(columns={'SK_ID_BUREAU': 'BUREAU_COUNT'})

In [54]:
bureau_agg.head()

   SK_ID_CURR  BUREAU_COUNT
0      100001             7
1      100002             8
2      100003             4
3      100004             2
4      100005             3

In [55]:
credit_active_dummies = pd.get_dummies(df_bureau['CREDIT_ACTIVE'])
credit_active_dummies["SK_ID_CURR"] = df_bureau["SK_ID_CURR"]
credit_active_counts = credit_active_dummies.groupby("SK_ID_CURR").sum().reset_index()

In [56]:
credit_type_dummies = pd.get_dummies(df_bureau['CREDIT_TYPE'])
credit_type_dummies["SK_ID_CURR"] = df_bureau['SK_ID_CURR']
credit_type_counts = credit_type_dummies.groupby("SK_ID_CURR").sum().reset_index()

bureau_agg = bureau_agg.merge(credit_type_counts, on='SK_ID_CURR', how='left')
bureau_agg

,SK_ID_CURR,BUREAU_COUNT,Another type of loan,Car loan,Cash loan (non-earmarked),Consumer credit,Credit card,Interbank credit,Loan for business development,Loan for purchase of shares (margin lending),Loan for the purchase of equipment,Loan for working capital replenishment,Microloan,Mobile operator loan,Mortgage,Real estate loan,Unknown type of loan
0,100001,7,0,0,0,7,0,0,0,0,0,0,0,0,0,0,0
1,100002,8,0,0,0,4,4,0,0,0,0,0,0,0,0,0,0
2,100003,4,0,0,0,2,2,0,0,0,0,0,0,0,0,0,0
3,100004,2,0,0,0,2,0,0,0,0,0,0,0,0,0,0,0
4,100005,3,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,1,0,0,9,3,0,0,0,0,0,0,0,0,0,0
305807,456250,3,0,0,0,2,1,0,0,0,0,0,0,0,0,0,0
305808,456253,4,0,0,0,3,1,0,0,0,0,0,0,0,0,0,0
305809,456254,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
305810,456255,11,0,0,0,9,2,0,0,0,0,0,0,0,0,0,0

In [57]:
credit_active_counts

        SK_ID_CURR  Active  Bad debt  Closed  Sold
0           100001       3         0       4     0
1           100002       2         0       6     0
2           100003       1         0       3     0
3           100004       0         0       2     0
4           100005       2         0       1     0
...            ...     ...       ...     ...   ...
305806      456249       2         0      11     0
305807      456250       2         0       1     0
305808      456253       2         0       2     0
305809      456254       0         0       1     0
305810      456255       5         0       6     0

[305811 rows x 5 columns]

In [58]:
bureau_agg = bureau_agg.merge(credit_active_counts, on='SK_ID_CURR', how='left')

In [59]:
bureau_agg

,SK_ID_CURR,BUREAU_COUNT,Another type of loan,Car loan,Cash loan (non-earmarked),Consumer credit,Credit card,Interbank credit,Loan for business development,Loan for purchase of shares (margin lending),...,Loan for working capital replenishment,Microloan,Mobile operator loan,Mortgage,Real estate loan,Unknown type of loan,Active,Bad debt,Closed,Sold
0,100001,7,0,0,0,7,0,0,0,0,...,0,0,0,0,0,0,3,0,4,0
1,100002,8,0,0,0,4,4,0,0,0,...,0,0,0,0,0,0,2,0,6,0
2,100003,4,0,0,0,2,2,0,0,0,...,0,0,0,0,0,0,1,0,3,0
3,100004,2,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,0,2,0
4,100005,3,0,0,0,2,1,0,0,0,...,0,0,0,0,0,0,2,0,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,1,0,0,9,3,0,0,0,...,0,0,0,0,0,0,2,0,11,0
305807,456250,3,0,0,0,2,1,0,0,0,...,0,0,0,0,0,0,2,0,1,0
305808,456253,4,0,0,0,3,1,0,0,0,...,0,0,0,0,0,0,2,0,2,0
305809,456254,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,1,0
305810,456255,11,0,0,0,9,2,0,0,0,...,0,0,0,0,0,0,5,0,6,0

In [60]:
df_bureau.columns

Index(['SK_ID_CURR', 'SK_ID_BUREAU', 'CREDIT_ACTIVE', 'CREDIT_CURRENCY',
       'DAYS_CREDIT', 'CREDIT_DAY_OVERDUE', 'DAYS_CREDIT_ENDDATE',
       'DAYS_ENDDATE_FACT', 'AMT_CREDIT_MAX_OVERDUE', 'CNT_CREDIT_PROLONG',
       'AMT_CREDIT_SUM', 'AMT_CREDIT_SUM_DEBT', 'AMT_CREDIT_SUM_LIMIT',
       'AMT_CREDIT_SUM_OVERDUE', 'CREDIT_TYPE', 'DAYS_CREDIT_UPDATE',
       'AMT_ANNUITY'],
      dtype='str')

In [61]:
df = df_bureau.groupby("SK_ID_CURR")["AMT_CREDIT_SUM_DEBT"].sum().reset_index()
df

        SK_ID_CURR  AMT_CREDIT_SUM_DEBT
0           100001           596686.500
1           100002           245781.000
2           100003                0.000
3           100004                0.000
4           100005           568408.500
...            ...                  ...
305806      456249           163071.000
305807      456250          2232040.095
305808      456253          1795833.000
305809      456254                0.000
305810      456255          1534913.010

[305811 rows x 2 columns]

In [62]:
bureau_agg = bureau_agg.merge(df, on='SK_ID_CURR', how='left')

In [63]:
bureau_agg

,SK_ID_CURR,BUREAU_COUNT,Another type of loan,Car loan,Cash loan (non-earmarked),Consumer credit,Credit card,Interbank credit,Loan for business development,Loan for purchase of shares (margin lending),...,Microloan,Mobile operator loan,Mortgage,Real estate loan,Unknown type of loan,Active,Bad debt,Closed,Sold,AMT_CREDIT_SUM_DEBT
0,100001,7,0,0,0,7,0,0,0,0,...,0,0,0,0,0,3,0,4,0,596686.500
1,100002,8,0,0,0,4,4,0,0,0,...,0,0,0,0,0,2,0,6,0,245781.000
2,100003,4,0,0,0,2,2,0,0,0,...,0,0,0,0,0,1,0,3,0,0.000
3,100004,2,0,0,0,2,0,0,0,0,...,0,0,0,0,0,0,0,2,0,0.000
4,100005,3,0,0,0,2,1,0,0,0,...,0,0,0,0,0,2,0,1,0,568408.500
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,1,0,0,9,3,0,0,0,...,0,0,0,0,0,2,0,11,0,163071.000
305807,456250,3,0,0,0,2,1,0,0,0,...,0,0,0,0,0,2,0,1,0,2232040.095
305808,456253,4,0,0,0,3,1,0,0,0,...,0,0,0,0,0,2,0,2,0,1795833.000
305809,456254,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,1,0,0.000
305810,456255,11,0,0,0,9,2,0,0,0,...,0,0,0,0,0,5,0,6,0,1534913.010

In [64]:
df = df_bureau.groupby("SK_ID_CURR")["AMT_CREDIT_MAX_OVERDUE"].max().reset_index()
bureau_agg = bureau_agg.merge(df, on='SK_ID_CURR', how='left')

In [65]:
df = df_bureau.groupby("SK_ID_CURR")["CREDIT_DAY_OVERDUE"].sum().reset_index()
bureau_agg = bureau_agg.merge(df, on='SK_ID_CURR', how='left')

In [66]:
bureau_agg

,SK_ID_CURR,BUREAU_COUNT,Another type of loan,Car loan,Cash loan (non-earmarked),Consumer credit,Credit card,Interbank credit,Loan for business development,Loan for purchase of shares (margin lending),...,Mortgage,Real estate loan,Unknown type of loan,Active,Bad debt,Closed,Sold,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_MAX_OVERDUE,CREDIT_DAY_OVERDUE
0,100001,7,0,0,0,7,0,0,0,0,...,0,0,0,3,0,4,0,596686.500,NaN,0
1,100002,8,0,0,0,4,4,0,0,0,...,0,0,0,2,0,6,0,245781.000,5043.645,0
2,100003,4,0,0,0,2,2,0,0,0,...,0,0,0,1,0,3,0,0.000,0.000,0
3,100004,2,0,0,0,2,0,0,0,0,...,0,0,0,0,0,2,0,0.000,0.000,0
4,100005,3,0,0,0,2,1,0,0,0,...,0,0,0,2,0,1,0,568408.500,0.000,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,1,0,0,9,3,0,0,0,...,0,0,0,2,0,11,0,163071.000,18945.000,0
305807,456250,3,0,0,0,2,1,0,0,0,...,0,0,0,2,0,1,0,2232040.095,0.000,0
305808,456253,4,0,0,0,3,1,0,0,0,...,0,0,0,2,0,2,0,1795833.000,NaN,0
305809,456254,1,0,0,0,1,0,0,0,0,...,0,0,0,0,0,1,0,0.000,NaN,0
305810,456255,11,0,0,0,9,2,0,0,0,...,0,0,0,5,0,6,0,1534913.010,25578.000,0

In [67]:

df = df_bureau.groupby("SK_ID_CURR")["CNT_CREDIT_PROLONG"].sum().reset_index()
bureau_agg = bureau_agg.merge(df, on='SK_ID_CURR', how='left')

In [68]:
df = df_bureau.groupby("SK_ID_CURR")["DAYS_CREDIT"].max().reset_index()

bureau_agg = bureau_agg.merge(df, on='SK_ID_CURR', how='left')

In [69]:
bureau_agg

,SK_ID_CURR,BUREAU_COUNT,Another type of loan,Car loan,Cash loan (non-earmarked),Consumer credit,Credit card,Interbank credit,Loan for business development,Loan for purchase of shares (margin lending),...,Unknown type of loan,Active,Bad debt,Closed,Sold,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_MAX_OVERDUE,CREDIT_DAY_OVERDUE,CNT_CREDIT_PROLONG,DAYS_CREDIT
0,100001,7,0,0,0,7,0,0,0,0,...,0,3,0,4,0,596686.500,NaN,0,0,-49
1,100002,8,0,0,0,4,4,0,0,0,...,0,2,0,6,0,245781.000,5043.645,0,0,-103
2,100003,4,0,0,0,2,2,0,0,0,...,0,1,0,3,0,0.000,0.000,0,0,-606
3,100004,2,0,0,0,2,0,0,0,0,...,0,0,0,2,0,0.000,0.000,0,0,-408
4,100005,3,0,0,0,2,1,0,0,0,...,0,2,0,1,0,568408.500,0.000,0,0,-62
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,1,0,0,9,3,0,0,0,...,0,2,0,11,0,163071.000,18945.000,0,0,-483
305807,456250,3,0,0,0,2,1,0,0,0,...,0,2,0,1,0,2232040.095,0.000,0,0,-760
305808,456253,4,0,0,0,3,1,0,0,0,...,0,2,0,2,0,1795833.000,NaN,0,0,-713
305809,456254,1,0,0,0,1,0,0,0,0,...,0,0,0,1,0,0.000,NaN,0,0,-1104
305810,456255,11,0,0,0,9,2,0,0,0,...,0,5,0,6,0,1534913.010,25578.000,0,1,-363

In [70]:
df = df_bureau.groupby("SK_ID_CURR")["AMT_CREDIT_SUM"].sum().reset_index()
bureau_agg = bureau_agg.merge(df, on='SK_ID_CURR', how='left')

In [71]:
df = df_bureau.groupby("SK_ID_CURR")["AMT_CREDIT_SUM_OVERDUE"].sum().reset_index()
bureau_agg = bureau_agg.merge(df, on='SK_ID_CURR', how='left')

In [72]:
df = df_bureau.groupby("SK_ID_CURR")["DAYS_CREDIT"].min().reset_index()
df = df.rename(columns={"DAYS_CREDIT": "DAYS_CREDIT_MIN"})
bureau_agg = bureau_agg.merge(df, on='SK_ID_CURR', how='left')

In [73]:
bureau_agg

,SK_ID_CURR,BUREAU_COUNT,Another type of loan,Car loan,Cash loan (non-earmarked),Consumer credit,Credit card,Interbank credit,Loan for business development,Loan for purchase of shares (margin lending),...,Closed,Sold,AMT_CREDIT_SUM_DEBT,AMT_CREDIT_MAX_OVERDUE,CREDIT_DAY_OVERDUE,CNT_CREDIT_PROLONG,DAYS_CREDIT,AMT_CREDIT_SUM,AMT_CREDIT_SUM_OVERDUE,DAYS_CREDIT_MIN
0,100001,7,0,0,0,7,0,0,0,0,...,4,0,596686.500,NaN,0,0,-49,1453365.000,0.0,-1572
1,100002,8,0,0,0,4,4,0,0,0,...,6,0,245781.000,5043.645,0,0,-103,865055.565,0.0,-1437
2,100003,4,0,0,0,2,2,0,0,0,...,3,0,0.000,0.000,0,0,-606,1017400.500,0.0,-2586
3,100004,2,0,0,0,2,0,0,0,0,...,2,0,0.000,0.000,0,0,-408,189037.800,0.0,-1326
4,100005,3,0,0,0,2,1,0,0,0,...,1,0,568408.500,0.000,0,0,-62,657126.000,0.0,-373
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
305806,456249,13,1,0,0,9,3,0,0,0,...,11,0,163071.000,18945.000,0,0,-483,3693858.660,0.0,-2713
305807,456250,3,0,0,0,2,1,0,0,0,...,1,0,2232040.095,0.000,0,0,-760,3086459.550,0.0,-1002
305808,456253,4,0,0,0,3,1,0,0,0,...,2,0,1795833.000,NaN,0,0,-713,3960000.000,0.0,-919
305809,456254,1,0,0,0,1,0,0,0,0,...,1,0,0.000,NaN,0,0,-1104,45000.000,0.0,-1104
305810,456255,11,0,0,0,9,2,0,0,0,...,6,0,1534913.010,25578.000,0,1,-363,3801919.500,0.0,-2337

In [74]:
df_bureaue_balance = pd.read_csv(r"C:\Users\hamza\Masaüstü\Mlops_Lecture_Project\data_folder\bureau_balance.csv" , encoding="unicode_escape")
df_bureaue_balance.head()

   SK_ID_BUREAU  MONTHS_BALANCE STATUS
0       5715448               0      C
1       5715448              -1      C
2       5715448              -2      C
3       5715448              -3      C
4       5715448              -4      C

In [75]:
len(df_bureaue_balance)

27299925

In [76]:
df_previous = pd.read_csv(r"C:\Users\hamza\Masaüstü\Mlops_Lecture_Project\data_folder\previous_application.csv")

In [89]:
df_previous.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'NAME_CONTRACT_TYPE', 'AMT_ANNUITY',
       'AMT_APPLICATION', 'AMT_CREDIT', 'AMT_DOWN_PAYMENT', 'AMT_GOODS_PRICE',
       'WEEKDAY_APPR_PROCESS_START', 'HOUR_APPR_PROCESS_START',
       'FLAG_LAST_APPL_PER_CONTRACT', 'NFLAG_LAST_APPL_IN_DAY',
       'RATE_DOWN_PAYMENT', 'RATE_INTEREST_PRIMARY',
       'RATE_INTEREST_PRIVILEGED', 'NAME_CASH_LOAN_PURPOSE',
       'NAME_CONTRACT_STATUS', 'DAYS_DECISION', 'NAME_PAYMENT_TYPE',
       'CODE_REJECT_REASON', 'NAME_TYPE_SUITE', 'NAME_CLIENT_TYPE',
       'NAME_GOODS_CATEGORY', 'NAME_PORTFOLIO', 'NAME_PRODUCT_TYPE',
       'CHANNEL_TYPE', 'SELLERPLACE_AREA', 'NAME_SELLER_INDUSTRY',
       'CNT_PAYMENT', 'NAME_YIELD_GROUP', 'PRODUCT_COMBINATION',
       'DAYS_FIRST_DRAWING', 'DAYS_FIRST_DUE', 'DAYS_LAST_DUE_1ST_VERSION',
       'DAYS_LAST_DUE', 'DAYS_TERMINATION', 'NFLAG_INSURED_ON_APPROVAL'],
      dtype='str')

In [78]:
df_previous.head()

,SK_ID_PREV,SK_ID_CURR,NAME_CONTRACT_TYPE,AMT_ANNUITY,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,AMT_GOODS_PRICE,WEEKDAY_APPR_PROCESS_START,HOUR_APPR_PROCESS_START,...,NAME_SELLER_INDUSTRY,CNT_PAYMENT,NAME_YIELD_GROUP,PRODUCT_COMBINATION,DAYS_FIRST_DRAWING,DAYS_FIRST_DUE,DAYS_LAST_DUE_1ST_VERSION,DAYS_LAST_DUE,DAYS_TERMINATION,NFLAG_INSURED_ON_APPROVAL
0,2030495,271877,Consumer loans,1730.430,17145.0,17145.0,0.0,17145.0,SATURDAY,15,...,Connectivity,12.0,middle,POS mobile with interest,365243.0,-42.0,300.0,-42.0,-37.0,0.0
1,2802425,108129,Cash loans,25188.615,607500.0,679671.0,NaN,607500.0,THURSDAY,11,...,XNA,36.0,low_action,Cash X-Sell: low,365243.0,-134.0,916.0,365243.0,365243.0,1.0
2,2523466,122040,Cash loans,15060.735,112500.0,136444.5,NaN,112500.0,TUESDAY,11,...,XNA,12.0,high,Cash X-Sell: high,365243.0,-271.0,59.0,365243.0,365243.0,1.0
3,2819243,176158,Cash loans,47041.335,450000.0,470790.0,NaN,450000.0,MONDAY,7,...,XNA,12.0,middle,Cash X-Sell: middle,365243.0,-482.0,-152.0,-182.0,-177.0,1.0
4,1784265,202054,Cash loans,31924.395,337500.0,404055.0,NaN,337500.0,THURSDAY,9,...,XNA,24.0,high,Cash Street: high,NaN,NaN,NaN,NaN,NaN,NaN

In [85]:
df_previous.columns
df_previous["SK_ID_CURR"] , df_previous["SK_ID_PREV"]

(0          271877
 1          108129
 2          122040
 3          176158
 4          202054
             ...
 1670209    352015
 1670210    334635
 1670211    249544
 1670212    400317
 1670213    261212
 Name: SK_ID_CURR, Length: 1670214, dtype: int64,
 0          2030495
 1          2802425
 2          2523466
 3          2819243
 4          1784265
             ...
 1670209    2300464
 1670210    2357031
 1670211    2659632
 1670212    2785582
 1670213    2418762
 Name: SK_ID_PREV, Length: 1670214, dtype: int64)

In [82]:
prev_agg = df_previous.groupby("SK_ID_CURR")["SK_ID_PREV"].count().reset_index()
prev_agg = prev_agg.rename(columns={"SK_ID_PREV": "PREV_APP_COUNT"})
prev_agg

        SK_ID_CURR  PREV_APP_COUNT
0           100001               1
1           100002               1
2           100003               3
3           100004               1
4           100005               2
...            ...             ...
338852      456251               1
338853      456252               1
338854      456253               2
338855      456254               2
338856      456255               8

[338857 rows x 2 columns]

In [86]:
dummies = pd.get_dummies(df_previous['NAME_CONTRACT_STATUS'])
dummies["SK_ID_CURR"] = df_previous['SK_ID_CURR']
dummies.groupby("SK_ID_CURR").sum().reset_index()
prev_agg = prev_agg.merge(dummies , on = "SK_ID_CURR" , how="left")

In [87]:
prev_agg

         SK_ID_CURR  PREV_APP_COUNT  Approved  Canceled  Refused  Unused offer
0            100001               1      True     False    False         False
1            100002               1      True     False    False         False
2            100003               3      True     False    False         False
3            100003               3      True     False    False         False
4            100003               3      True     False    False         False
...             ...             ...       ...       ...      ...           ...
1670209      456255               8      True     False    False         False
1670210      456255               8     False     False     True         False
1670211      456255               8     False     False     True         False
1670212      456255               8      True     False    False         False
1670213      456255               8      True     False    False         False

[1670214 rows x 6 columns]

In [90]:
mean_app=df_previous.groupby("SK_ID_CURR")["AMT_APPLICATION"].mean()
mean_app

SK_ID_CURR
100001     24835.500
100002    179055.000
100003    435436.500
100004     24282.000
100005     22308.750
             ...
456251     40455.000
456252     57595.500
456253     24162.750
456254    121317.750
456255    362770.875
Name: AMT_APPLICATION, Length: 338857, dtype: float64

In [91]:
prev_agg = prev_agg.merge(mean_app , on="SK_ID_CURR" , how = "left")

In [92]:
received_app=df_previous.groupby("SK_ID_CURR")["AMT_CREDIT"].mean()
received_app

SK_ID_CURR
100001     23787.00
100002    179055.00
100003    484191.00
100004     20106.00
100005     20076.75
            ...
456251     40455.00
456252     56821.50
456253     20625.75
456254    134439.75
456255    424431.00
Name: AMT_CREDIT, Length: 338857, dtype: float64

In [93]:
prev_agg = prev_agg.merge(received_app , on="SK_ID_CURR" , how = "left")

In [94]:
annutıy=df_previous.groupby("SK_ID_CURR")["AMT_ANNUITY"].mean()
annutıy

SK_ID_CURR
100001     3951.000000
100002     9251.775000
100003    56553.990000
100004     5357.250000
100005     4813.200000
              ...
456251     6605.910000
456252    10074.465000
456253     4770.405000
456254    10681.132500
456255    20775.391875
Name: AMT_ANNUITY, Length: 338857, dtype: float64

In [ ]:
prev_agg = prev_agg.merge(received_app , on="SK_ID_CURR" , how = "left")

In [95]:
down_payment=df_previous.groupby("SK_ID_CURR")["AMT_DOWN_PAYMENT"].mean()
down_payment

SK_ID_CURR
100001    2520.00
100002       0.00
100003    3442.50
100004    4860.00
100005    4464.00
           ...
456251       0.00
456252    3456.00
456253    4403.25
456254       0.00
456255    4941.00
Name: AMT_DOWN_PAYMENT, Length: 338857, dtype: float64

In [96]:
prev_agg = prev_agg.merge(down_payment , on="SK_ID_CURR" , how = "left")

In [97]:
rate_ınterest=df_previous.groupby("SK_ID_CURR")["RATE_INTEREST_PRIMARY"].mean()
rate_ınterest

SK_ID_CURR
100001   NaN
100002   NaN
100003   NaN
100004   NaN
100005   NaN
          ..
456251   NaN
456252   NaN
456253   NaN
456254   NaN
456255   NaN
Name: RATE_INTEREST_PRIMARY, Length: 338857, dtype: float64

In [98]:
prev_agg = prev_agg.merge(rate_ınterest , on="SK_ID_CURR" , how = "left")

In [99]:
cnt_payment=df_previous.groupby("SK_ID_CURR")["CNT_PAYMENT"].mean()
cnt_payment

SK_ID_CURR
100001     8.00
100002    24.00
100003    10.00
100004     4.00
100005    12.00
          ...
456251     8.00
456252     6.00
456253     5.00
456254    15.00
456255    21.75
Name: CNT_PAYMENT, Length: 338857, dtype: float64

In [100]:
prev_agg = prev_agg.merge(cnt_payment , on="SK_ID_CURR" , how = "left")

In [101]:
days_decision=df_previous.groupby("SK_ID_CURR")["DAYS_DECISION"].max()
days_decision

SK_ID_CURR
100001   -1740
100002    -606
100003    -746
100004    -815
100005    -315
          ...
456251    -273
456252   -2497
456253   -1909
456254    -277
456255    -171
Name: DAYS_DECISION, Length: 338857, dtype: int64

In [102]:
prev_agg = prev_agg.merge(days_decision, on = "SK_ID_CURR" , how="left")

In [103]:
prev_agg

,SK_ID_CURR,PREV_APP_COUNT,Approved,Canceled,Refused,Unused offer,AMT_APPLICATION,AMT_CREDIT,AMT_DOWN_PAYMENT,RATE_INTEREST_PRIMARY,CNT_PAYMENT,DAYS_DECISION
0,100001,1,True,False,False,False,24835.500,23787.0,2520.0,NaN,8.00,-1740
1,100002,1,True,False,False,False,179055.000,179055.0,0.0,NaN,24.00,-606
2,100003,3,True,False,False,False,435436.500,484191.0,3442.5,NaN,10.00,-746
3,100003,3,True,False,False,False,435436.500,484191.0,3442.5,NaN,10.00,-746
4,100003,3,True,False,False,False,435436.500,484191.0,3442.5,NaN,10.00,-746
...,...,...,...,...,...,...,...,...,...,...,...,...
1670209,456255,8,True,False,False,False,362770.875,424431.0,4941.0,NaN,21.75,-171
1670210,456255,8,False,False,True,False,362770.875,424431.0,4941.0,NaN,21.75,-171
1670211,456255,8,False,False,True,False,362770.875,424431.0,4941.0,NaN,21.75,-171
1670212,456255,8,True,False,False,False,362770.875,424431.0,4941.0,NaN,21.75,-171
1670213,456255,8,True,False,False,False,362770.875,424431.0,4941.0,NaN,21.75,-171

In [3]:
import pandas as pd
df_credit_card_balance = pd.read_csv(r"C:\Users\hamza\Masaüstü\Mlops_Lecture_Project\data_folder\credit_card_balance.csv" , encoding="unicode-escape")

In [4]:
df_credit_card_balance

,SK_ID_PREV,SK_ID_CURR,MONTHS_BALANCE,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_DRAWINGS_OTHER_CURRENT,AMT_DRAWINGS_POS_CURRENT,AMT_INST_MIN_REGULARITY,...,AMT_RECIVABLE,AMT_TOTAL_RECEIVABLE,CNT_DRAWINGS_ATM_CURRENT,CNT_DRAWINGS_CURRENT,CNT_DRAWINGS_OTHER_CURRENT,CNT_DRAWINGS_POS_CURRENT,CNT_INSTALMENT_MATURE_CUM,NAME_CONTRACT_STATUS,SK_DPD,SK_DPD_DEF
0,2562384,378907,-6,56.970,135000,0.0,877.5,0.0,877.5,1700.325,...,0.000,0.000,0.0,1,0.0,1.0,35.0,Active,0,0
1,2582071,363914,-1,63975.555,45000,2250.0,2250.0,0.0,0.0,2250.000,...,64875.555,64875.555,1.0,1,0.0,0.0,69.0,Active,0,0
2,1740877,371185,-7,31815.225,450000,0.0,0.0,0.0,0.0,2250.000,...,31460.085,31460.085,0.0,0,0.0,0.0,30.0,Active,0,0
3,1389973,337855,-4,236572.110,225000,2250.0,2250.0,0.0,0.0,11795.760,...,233048.970,233048.970,1.0,1,0.0,0.0,10.0,Active,0,0
4,1891521,126868,-1,453919.455,450000,0.0,11547.0,0.0,11547.0,22924.890,...,453919.455,453919.455,0.0,1,0.0,1.0,101.0,Active,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3840307,1036507,328243,-9,0.000,45000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840308,1714892,347207,-9,0.000,45000,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,23.0,Active,0,0
3840309,1302323,215757,-9,275784.975,585000,270000.0,270000.0,0.0,0.0,2250.000,...,273093.975,273093.975,2.0,2,0.0,0.0,18.0,Active,0,0
3840310,1624872,430337,-10,0.000,450000,NaN,0.0,NaN,NaN,0.000,...,0.000,0.000,NaN,0,NaN,NaN,0.0,Active,0,0
3840311,2411345,236760,-10,0.000,157500,0.0,0.0,0.0,0.0,0.000,...,0.000,0.000,0.0,0,0.0,0.0,21.0,Completed,0,0

In [39]:
df_credit_card_balance.columns

Index(['SK_ID_PREV', 'SK_ID_CURR', 'MONTHS_BALANCE', 'AMT_BALANCE',
       'AMT_CREDIT_LIMIT_ACTUAL', 'AMT_DRAWINGS_ATM_CURRENT',
       'AMT_DRAWINGS_CURRENT', 'AMT_DRAWINGS_OTHER_CURRENT',
       'AMT_DRAWINGS_POS_CURRENT', 'AMT_INST_MIN_REGULARITY',
       'AMT_PAYMENT_CURRENT', 'AMT_PAYMENT_TOTAL_CURRENT',
       'AMT_RECEIVABLE_PRINCIPAL', 'AMT_RECIVABLE', 'AMT_TOTAL_RECEIVABLE',
       'CNT_DRAWINGS_ATM_CURRENT', 'CNT_DRAWINGS_CURRENT',
       'CNT_DRAWINGS_OTHER_CURRENT', 'CNT_DRAWINGS_POS_CURRENT',
       'CNT_INSTALMENT_MATURE_CUM', 'NAME_CONTRACT_STATUS', 'SK_DPD',
       'SK_DPD_DEF'],
      dtype='str')

In [40]:
cc_agg = df_credit_card_balance.groupby(['SK_ID_CURR'])["SK_ID_PREV"].count().reset_index()
cc_agg

        SK_ID_CURR  SK_ID_PREV
0           100006           6
1           100011          74
2           100013          96
3           100021          17
4           100023           8
...            ...         ...
103553      456244          41
103554      456246           8
103555      456247          95
103556      456248          23
103557      456250          12

[103558 rows x 2 columns]

In [41]:
cc_agg.rename(columns={"SK_ID_PREV":"CC_COUNT"} ,inplace=True)

In [42]:
sk_dpd=df_credit_card_balance.groupby("SK_ID_CURR")["SK_DPD"].max()

In [43]:
cc_agg = cc_agg.merge(sk_dpd , on = "SK_ID_CURR" , how="left")

In [45]:
sk_dpd_mean=df_credit_card_balance.groupby("SK_ID_CURR")["SK_DPD"].mean().reset_index()
sk_dpd_mean = sk_dpd_mean.rename(columns = {"SK_DPD" : "SK_DPD_MEAN"})

In [46]:
cc_agg = cc_agg.merge(sk_dpd_mean , on = "SK_ID_CURR" , how="left" ,)

In [47]:
cc_agg

        SK_ID_CURR  CC_COUNT  SK_DPD  SK_DPD_MEAN
0           100006         6       0     0.000000
1           100011        74       0     0.000000
2           100013        96       1     0.010417
3           100021        17       0     0.000000
4           100023         8       0     0.000000
...            ...       ...     ...          ...
103553      456244        41       0     0.000000
103554      456246         8       0     0.000000
103555      456247        95       1     0.031579
103556      456248        23       0     0.000000
103557      456250        12       0     0.000000

[103558 rows x 4 columns]

In [48]:
df = df_credit_card_balance.groupby("SK_ID_CURR")["AMT_BALANCE"].mean().reset_index()

In [49]:
df

        SK_ID_CURR    AMT_BALANCE
0           100006       0.000000
1           100011   54482.111149
2           100013   18159.919219
3           100021       0.000000
4           100023       0.000000
...            ...            ...
103553      456244  131834.730732
103554      456246   13136.731875
103555      456247   23216.396211
103556      456248       0.000000
103557      456250  173589.326250

[103558 rows x 2 columns]

In [50]:
cc_agg = cc_agg.merge(df , on = "SK_ID_CURR" , how = "left")

In [51]:
cc_agg

        SK_ID_CURR  CC_COUNT  SK_DPD  SK_DPD_MEAN    AMT_BALANCE
0           100006         6       0     0.000000       0.000000
1           100011        74       0     0.000000   54482.111149
2           100013        96       1     0.010417   18159.919219
3           100021        17       0     0.000000       0.000000
4           100023         8       0     0.000000       0.000000
...            ...       ...     ...          ...            ...
103553      456244        41       0     0.000000  131834.730732
103554      456246         8       0     0.000000   13136.731875
103555      456247        95       1     0.031579   23216.396211
103556      456248        23       0     0.000000       0.000000
103557      456250        12       0     0.000000  173589.326250

[103558 rows x 5 columns]

In [52]:
df = df_credit_card_balance.groupby("SK_ID_CURR")["AMT_CREDIT_LIMIT_ACTUAL"].mean().reset_index()

In [53]:
cc_agg = cc_agg.merge(df , on = "SK_ID_CURR" , how = "left")
cc_agg

,SK_ID_CURR,CC_COUNT,SK_DPD,SK_DPD_MEAN,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL
0,100006,6,0,0.000000,0.000000,270000.000000
1,100011,74,0,0.000000,54482.111149,164189.189189
2,100013,96,1,0.010417,18159.919219,131718.750000
3,100021,17,0,0.000000,0.000000,675000.000000
4,100023,8,0,0.000000,0.000000,135000.000000
...,...,...,...,...,...,...
103553,456244,41,0,0.000000,131834.730732,296341.463415
103554,456246,8,0,0.000000,13136.731875,135000.000000
103555,456247,95,1,0.031579,23216.396211,144000.000000
103556,456248,23,0,0.000000,0.000000,900000.000000
103557,456250,12,0,0.000000,173589.326250,178875.000000

In [54]:
df = df_credit_card_balance.groupby("SK_ID_CURR")["AMT_DRAWINGS_ATM_CURRENT"].mean().reset_index()
cc_agg = cc_agg.merge(df , on = "SK_ID_CURR" , how = "left")
cc_agg

,SK_ID_CURR,CC_COUNT,SK_DPD,SK_DPD_MEAN,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT
0,100006,6,0,0.000000,0.000000,270000.000000,NaN
1,100011,74,0,0.000000,54482.111149,164189.189189,2432.432432
2,100013,96,1,0.010417,18159.919219,131718.750000,6350.000000
3,100021,17,0,0.000000,0.000000,675000.000000,NaN
4,100023,8,0,0.000000,0.000000,135000.000000,NaN
...,...,...,...,...,...,...,...
103553,456244,41,0,0.000000,131834.730732,296341.463415,24475.609756
103554,456246,8,0,0.000000,13136.731875,135000.000000,0.000000
103555,456247,95,1,0.031579,23216.396211,144000.000000,2136.315789
103556,456248,23,0,0.000000,0.000000,900000.000000,NaN
103557,456250,12,0,0.000000,173589.326250,178875.000000,15000.000000

In [55]:
df = df_credit_card_balance.groupby("SK_ID_CURR")["AMT_DRAWINGS_CURRENT"].mean().reset_index()
cc_agg = cc_agg.merge(df , on = "SK_ID_CURR" , how = "left")
cc_agg

,SK_ID_CURR,CC_COUNT,SK_DPD,SK_DPD_MEAN,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT
0,100006,6,0,0.000000,0.000000,270000.000000,NaN,0.000000
1,100011,74,0,0.000000,54482.111149,164189.189189,2432.432432,2432.432432
2,100013,96,1,0.010417,18159.919219,131718.750000,6350.000000,5953.125000
3,100021,17,0,0.000000,0.000000,675000.000000,NaN,0.000000
4,100023,8,0,0.000000,0.000000,135000.000000,NaN,0.000000
...,...,...,...,...,...,...,...,...
103553,456244,41,0,0.000000,131834.730732,296341.463415,24475.609756,26842.388049
103554,456246,8,0,0.000000,13136.731875,135000.000000,0.000000,15199.256250
103555,456247,95,1,0.031579,23216.396211,144000.000000,2136.315789,2149.506474
103556,456248,23,0,0.000000,0.000000,900000.000000,NaN,0.000000
103557,456250,12,0,0.000000,173589.326250,178875.000000,15000.000000,15000.000000

In [56]:
df = df_credit_card_balance.groupby("SK_ID_CURR")["AMT_PAYMENT_CURRENT"].mean().reset_index()
cc_agg = cc_agg.merge(df , on = "SK_ID_CURR" , how = "left")
cc_agg

,SK_ID_CURR,CC_COUNT,SK_DPD,SK_DPD_MEAN,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_PAYMENT_CURRENT
0,100006,6,0,0.000000,0.000000,270000.000000,NaN,0.000000,NaN
1,100011,74,0,0.000000,54482.111149,164189.189189,2432.432432,2432.432432,4843.064189
2,100013,96,1,0.010417,18159.919219,131718.750000,6350.000000,5953.125000,7168.346250
3,100021,17,0,0.000000,0.000000,675000.000000,NaN,0.000000,NaN
4,100023,8,0,0.000000,0.000000,135000.000000,NaN,0.000000,NaN
...,...,...,...,...,...,...,...,...,...
103553,456244,41,0,0.000000,131834.730732,296341.463415,24475.609756,26842.388049,32720.544878
103554,456246,8,0,0.000000,13136.731875,135000.000000,0.000000,15199.256250,18778.275000
103555,456247,95,1,0.031579,23216.396211,144000.000000,2136.315789,2149.506474,4883.755263
103556,456248,23,0,0.000000,0.000000,900000.000000,NaN,0.000000,NaN
103557,456250,12,0,0.000000,173589.326250,178875.000000,15000.000000,15000.000000,10748.250000

In [57]:
df = df_credit_card_balance.groupby("SK_ID_CURR")["AMT_PAYMENT_TOTAL_CURRENT"].mean().reset_index()
cc_agg = cc_agg.merge(df , on = "SK_ID_CURR" , how = "left")
cc_agg

,SK_ID_CURR,CC_COUNT,SK_DPD,SK_DPD_MEAN,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT
0,100006,6,0,0.000000,0.000000,270000.000000,NaN,0.000000,NaN,0.000000
1,100011,74,0,0.000000,54482.111149,164189.189189,2432.432432,2432.432432,4843.064189,4520.067568
2,100013,96,1,0.010417,18159.919219,131718.750000,6350.000000,5953.125000,7168.346250,6817.172344
3,100021,17,0,0.000000,0.000000,675000.000000,NaN,0.000000,NaN,0.000000
4,100023,8,0,0.000000,0.000000,135000.000000,NaN,0.000000,NaN,0.000000
...,...,...,...,...,...,...,...,...,...,...
103553,456244,41,0,0.000000,131834.730732,296341.463415,24475.609756,26842.388049,32720.544878,32720.544878
103554,456246,8,0,0.000000,13136.731875,135000.000000,0.000000,15199.256250,18778.275000,15554.340000
103555,456247,95,1,0.031579,23216.396211,144000.000000,2136.315789,2149.506474,4883.755263,4115.878105
103556,456248,23,0,0.000000,0.000000,900000.000000,NaN,0.000000,NaN,0.000000
103557,456250,12,0,0.000000,173589.326250,178875.000000,15000.000000,15000.000000,10748.250000,1622.820000

In [58]:

df = df_credit_card_balance.groupby("SK_ID_CURR")["AMT_RECEIVABLE_PRINCIPAL"].mean().reset_index()
cc_agg = cc_agg.merge(df , on = "SK_ID_CURR" , how = "left")
cc_agg

,SK_ID_CURR,CC_COUNT,SK_DPD,SK_DPD_MEAN,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL
0,100006,6,0,0.000000,0.000000,270000.000000,NaN,0.000000,NaN,0.000000,0.000000
1,100011,74,0,0.000000,54482.111149,164189.189189,2432.432432,2432.432432,4843.064189,4520.067568,52402.088919
2,100013,96,1,0.010417,18159.919219,131718.750000,6350.000000,5953.125000,7168.346250,6817.172344,17255.559844
3,100021,17,0,0.000000,0.000000,675000.000000,NaN,0.000000,NaN,0.000000,0.000000
4,100023,8,0,0.000000,0.000000,135000.000000,NaN,0.000000,NaN,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...
103553,456244,41,0,0.000000,131834.730732,296341.463415,24475.609756,26842.388049,32720.544878,32720.544878,127608.373537
103554,456246,8,0,0.000000,13136.731875,135000.000000,0.000000,15199.256250,18778.275000,15554.340000,12883.016250
103555,456247,95,1,0.031579,23216.396211,144000.000000,2136.315789,2149.506474,4883.755263,4115.878105,22100.653895
103556,456248,23,0,0.000000,0.000000,900000.000000,NaN,0.000000,NaN,0.000000,0.000000
103557,456250,12,0,0.000000,173589.326250,178875.000000,15000.000000,15000.000000,10748.250000,1622.820000,168446.591250

In [59]:
df_credit_card_balance["CREDIT_UTILIZATION"] = df_credit_card_balance["AMT_BALANCE"] / df_credit_card_balance["AMT_CREDIT_LIMIT_ACTUAL"]
df = df_credit_card_balance.groupby("SK_ID_CURR")["CREDIT_UTILIZATION"].mean().reset_index()
cc_agg = cc_agg.merge(df , on = "SK_ID_CURR" , how = "left")
cc_agg

,SK_ID_CURR,CC_COUNT,SK_DPD,SK_DPD_MEAN,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,CREDIT_UTILIZATION
0,100006,6,0,0.000000,0.000000,270000.000000,NaN,0.000000,NaN,0.000000,0.000000,0.000000
1,100011,74,0,0.000000,54482.111149,164189.189189,2432.432432,2432.432432,4843.064189,4520.067568,52402.088919,0.302678
2,100013,96,1,0.010417,18159.919219,131718.750000,6350.000000,5953.125000,7168.346250,6817.172344,17255.559844,0.115301
3,100021,17,0,0.000000,0.000000,675000.000000,NaN,0.000000,NaN,0.000000,0.000000,0.000000
4,100023,8,0,0.000000,0.000000,135000.000000,NaN,0.000000,NaN,0.000000,0.000000,0.000000
...,...,...,...,...,...,...,...,...,...,...,...,...
103553,456244,41,0,0.000000,131834.730732,296341.463415,24475.609756,26842.388049,32720.544878,32720.544878,127608.373537,0.444874
103554,456246,8,0,0.000000,13136.731875,135000.000000,0.000000,15199.256250,18778.275000,15554.340000,12883.016250,0.097309
103555,456247,95,1,0.031579,23216.396211,144000.000000,2136.315789,2149.506474,4883.755263,4115.878105,22100.653895,0.161225
103556,456248,23,0,0.000000,0.000000,900000.000000,NaN,0.000000,NaN,0.000000,0.000000,0.000000
103557,456250,12,0,0.000000,173589.326250,178875.000000,15000.000000,15000.000000,10748.250000,1622.820000,168446.591250,0.970018

In [61]:
df_dummies = pd.get_dummies(df_credit_card_balance['NAME_CONTRACT_STATUS'])
df_dummies["SK_ID_CURR"] = df_credit_card_balance["SK_ID_CURR"]
df_dummies = df_dummies.groupby("SK_ID_CURR").sum().reset_index()

cc_agg = cc_agg.merge(df_dummies , on = "SK_ID_CURR",  how= "left")

In [62]:
cc_agg

,SK_ID_CURR,CC_COUNT,SK_DPD,SK_DPD_MEAN,AMT_BALANCE,AMT_CREDIT_LIMIT_ACTUAL,AMT_DRAWINGS_ATM_CURRENT,AMT_DRAWINGS_CURRENT,AMT_PAYMENT_CURRENT,AMT_PAYMENT_TOTAL_CURRENT,AMT_RECEIVABLE_PRINCIPAL,CREDIT_UTILIZATION,Active,Approved,Completed,Demand,Refused,Sent proposal,Signed
0,100006,6,0,0.000000,0.000000,270000.000000,NaN,0.000000,NaN,0.000000,0.000000,0.000000,6,0,0,0,0,0,0
1,100011,74,0,0.000000,54482.111149,164189.189189,2432.432432,2432.432432,4843.064189,4520.067568,52402.088919,0.302678,74,0,0,0,0,0,0
2,100013,96,1,0.010417,18159.919219,131718.750000,6350.000000,5953.125000,7168.346250,6817.172344,17255.559844,0.115301,96,0,0,0,0,0,0
3,100021,17,0,0.000000,0.000000,675000.000000,NaN,0.000000,NaN,0.000000,0.000000,0.000000,7,0,10,0,0,0,0
4,100023,8,0,0.000000,0.000000,135000.000000,NaN,0.000000,NaN,0.000000,0.000000,0.000000,8,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103553,456244,41,0,0.000000,131834.730732,296341.463415,24475.609756,26842.388049,32720.544878,32720.544878,127608.373537,0.444874,36,0,5,0,0,0,0
103554,456246,8,0,0.000000,13136.731875,135000.000000,0.000000,15199.256250,18778.275000,15554.340000,12883.016250,0.097309,8,0,0,0,0,0,0
103555,456247,95,1,0.031579,23216.396211,144000.000000,2136.315789,2149.506474,4883.755263,4115.878105,22100.653895,0.161225,95,0,0,0,0,0,0
103556,456248,23,0,0.000000,0.000000,900000.000000,NaN,0.000000,NaN,0.000000,0.000000,0.000000,23,0,0,0,0,0,0
103557,456250,12,0,0.000000,173589.326250,178875.000000,15000.000000,15000.000000,10748.250000,1622.820000,168446.591250,0.970018,12,0,0,0,0,0,0

In [ ]:
df_pos = pd.read_csv(r"C:\Users\hamza\Masaüstü\Mlops_Lecture_Project\data_folder\POS_CASH_balance.csv", encoding="unicode_escape")

pos_agg = df_pos.groupby("SK_ID_CURR")["SK_ID_PREV"].count().reset_index()
pos_agg = pos_agg.rename(columns={"SK_ID_PREV": "POS_COUNT"})

for col, func, name in [
    ("SK_DPD", "max", "SK_DPD_MAX"),
    ("SK_DPD", "mean", "SK_DPD_MEAN"),
    ("SK_DPD_DEF", "max", "SK_DPD_DEF_MAX"),
    ("SK_DPD_DEF", "mean", "SK_DPD_DEF_MEAN"),
    ("CNT_INSTALMENT", "mean", "CNT_INSTALMENT_MEAN"),
    ("CNT_INSTALMENT_FUTURE", "mean", "CNT_INSTALMENT_FUTURE_MEAN"),
]:
    df = df_pos.groupby("SK_ID_CURR")[col].agg(func).reset_index()
    df = df.rename(columns={col: name})
    pos_agg = pos_agg.merge(df, on="SK_ID_CURR", how="left")

dummies = pd.get_dummies(df_pos["NAME_CONTRACT_STATUS"])
dummies["SK_ID_CURR"] = df_pos["SK_ID_CURR"]
status_counts = dummies.groupby("SK_ID_CURR").sum().reset_index()
pos_agg = pos_agg.merge(status_counts, on="SK_ID_CURR", how="left")

In [ ]:
pos_agg

In [ ]:
df_inst = pd.read_csv(r"C:\Users\hamza\Masaüstü\Mlops_Lecture_Project\data_folder\installments_payments.csv", encoding="unicode_escape")

inst_agg = df_inst.groupby("SK_ID_CURR")["SK_ID_PREV"].count().reset_index()
inst_agg = inst_agg.rename(columns={"SK_ID_PREV": "INST_COUNT"})

df_inst["DAYS_LATE"] = df_inst["DAYS_ENTRY_PAYMENT"] - df_inst["DAYS_INSTALMENT"]
df_inst["PAYMENT_RATIO"] = df_inst["AMT_PAYMENT"] / df_inst["AMT_INSTALMENT"]

for col, func, name in [
    ("DAYS_LATE", "mean", "DAYS_LATE_MEAN"),
    ("DAYS_LATE", "max", "DAYS_LATE_MAX"),
    ("PAYMENT_RATIO", "mean", "PAYMENT_RATIO_MEAN"),
    ("AMT_INSTALMENT", "mean", "AMT_INSTALMENT_MEAN"),
    ("AMT_PAYMENT", "mean", "AMT_PAYMENT_MEAN"),
]:
    df = df_inst.groupby("SK_ID_CURR")[col].agg(func).reset_index()
    df = df.rename(columns={col: name})
    inst_agg = inst_agg.merge(df, on="SK_ID_CURR", how="left")

In [ ]:
inst_agg

In [ ]:
bb = df_bureaue_balance.merge(df_bureau[["SK_ID_BUREAU", "SK_ID_CURR"]], on="SK_ID_BUREAU", how="left")

bb_agg = bb.groupby("SK_ID_CURR")["MONTHS_BALANCE"].count().reset_index()
bb_agg = bb_agg.rename(columns={"MONTHS_BALANCE": "BB_MONTHS_COUNT"})

dummies = pd.get_dummies(bb["STATUS"])
dummies["SK_ID_CURR"] = bb["SK_ID_CURR"]
status_counts = dummies.groupby("SK_ID_CURR").sum().reset_index()
bb_agg = bb_agg.merge(status_counts, on="SK_ID_CURR", how="left")

In [ ]:
bb_agg